menus = ['breakfast', 'lunch', 'dinner', 'dessert']

meal_data = [['breakfast', 'Eggs', 'Eggs Benedict', '12.00', '4'],
['breakfast', 'Eggs', 'Creamy Omelet', '10.00', '3'],
['breakfast', 'Eggs', 'Bacon and Egg Sandwich', '12.50', '5'],
['breakfast', 'Bacon', 'Bacon Wrapped Bacon', '12.00', '4'],
['breakfast', 'Bacon', 'Bacon and Egg Sandwich', '12.50', '3'],
['breakfast', 'Bacon', 'Bacon Cheesepuffs', '11.00', '2'],
['breakfast', 'Pancakes', 'Bluebuerry Pancake', '13.50', '3'],
['breakfast', 'Pancakes', 'Chocolate Chip Pancake', '13.50', '5'],
['breakfast', 'Pancakes', 'Raspberry Pancake', '13.50', '4'],
['breakfast', 'Waffles', 'Triple Waffle Stack', '11.50', '5'],
['breakfast', 'Waffles', 'Double Waffle Stack', '10.50', '4'],
['breakfast', 'Waffles', 'Chocolate Chip Waffles', '11.50', '5'],
['lunch', 'Sandwich', 'Pastrami Sandwich', '13.50', '2'],
['lunch', 'Sandwich', 'Club Sandwich', '11.50', '4'],
['lunch', 'Sandwich', 'Grilled Chicken Sandwich', '13.50', '5'],
['lunch', 'Sandwich', 'Grilled Cheese Ssandwich', '12.00', '3'],
['lunch', 'Soup', 'Tomato Soup', '10.00', '3'],
['lunch', 'Soup', 'Clam Chowder', '11.00', '5'],
['lunch', 'Soup', 'French Onion Soup', '12.00', '2'],
['lunch', 'Soup', 'Chicken Noodle Soup', '10.00', '3'],
['lunch', 'Chicken', 'Chicken Alfredo', '14.00', '4'],
['lunch', 'Chicken', 'Grilled Chicken Sandwich', '13.50', '5'],
['lunch', 'Chicken', 'Chicken Noodle Soup', '10.00', '3'],
['lunch', 'Chicken', 'Chicken Wings (Hot)', '15.00', '2'],
['lunch', 'Chicken', 'Chicken Wings (Mild)', '15.00', '4'],
['lunch', 'Chicken', 'Chicken Wings (Boneless)', '13.50', '5'],
['lunch', 'Chicken', 'Chicken Pot Pie', '12.00', '3'],
['lunch', 'Chicken', 'Stuffed Chicken Breast', '13.00', '2'],
['lunch', 'Chicken', 'Chicken and Rice', '13.50', '4'],
['dinner', 'Steak', 'Steak and Potatoes', '15.00', '3'],
['dinner', 'Steak', 'Carne Asada', '15.00', '5'],
['dinner', 'Steak', 'Filet Mignon', '16.00', '5'],
['dinner', 'Steak', 'Steak Tenderloin', '17.50', '4'],
['dinner', 'Steak', 'Steak Fajitas', '16.00', '5'],
['dinner', 'Cheeseburger', 'Cheeseburger with Bacon', '12.50', '4'],
['dinner', 'Cheeseburger', 'Cheeseburger with Fries', '14.00', '4'],
['dinner', 'Cheeseburger', 'Cheeseburger with Onion Rings', '14.00', '3'],
['dinner', 'Cheeseburger', 'Classic Cheeseburger', '12.50', '3'],
['dinner', 'Italian', 'Chicken Alfredo', '14.00', '2'],
['dinner', 'Italian', 'Fettuccini Alfredo', '16.00', '3'],
['dinner', 'Italian', 'Calzone', '15.00', '2'],
['dinner', 'Italian', 'Pizza', '17.00', '4'],
['dinner', 'Italian', 'Italian Salad', '12.00', '5'],
['dinner', 'Noodles', 'Spaghetti and Meatballs', '12.50', '4'],
['dinner', 'Noodles', 'Stir Fry', '14.50', '3'],
['dinner', 'Noodles', 'Lasagna', '14.00', '4'],
['dinner', 'Noodles', 'Chicken Alfredo', '14.00', '2'],
['dessert', 'Ice Cream', 'Chocolate', '10.00', '3'],
['dessert', 'Ice Cream', 'Vanilla', '10.00', '2'],
['dessert', 'Ice Cream', 'Strawberry', '10.00', '3'],
['dessert', 'Pie', 'Blueberry Pie', '15.00', '4'],
['dessert', 'Pie', 'Blackberry Pie', '15.00', '3'],
['dessert', 'Pie', 'Apple Pie', '15.00', '5'],
['dessert', 'Cupcake', 'Red Velvet Cupcake', '12.00', '6'],
['dessert', 'Cupcake', 'Triple Chocolate Cupcake', '12.00', '4'],
['dessert', 'Cupcake', 'Rainbow Cupcake', '12.00', '2'],
['dessert', 'Milkshake', 'Peanut Butter', '10.00', '4'],
['dessert', 'Milkshake', 'Strawberry', '10.00', '3'],
['dessert', 'Milkshake', 'Blueberry', '10.00', '3'],
['dessert', 'Milkshake', 'Chocolate', '10.00', '5'],
['dessert', 'Milkshake', 'Vanilla', '10.00', '5']]