#Welcome To Restaurant

def welcome_to():
    print("                   /\                   ")
    print("       |###       /  \          |###    ")
    print("       |         /    \         |       ")
    print("       |        /      \        |       ")
    print("       /\      /  ____  \      /\       ")
    print("      /  \    /  |    |  \    /  \      ")
    print("     /    \  /   |‾‾‾‾|   \  /    \     ")
    print("    / ___  \/     ‾‾‾‾     \/  ___ \    ")
    print("   / |   |  |              |  |   | \   ")
    print("  /  |   |  |              |  |   |  \  ")
    print(" /    ‾‾‾                      ‾‾‾    \ ")
    print(" |             |‾‾‾||‾‾‾|             | ")
    print(" |             |   ||   |             | ")
    print(" |    ___      |___||___|      ___    | ")
    print(" |   |   |     |   ||   |     |   |   | ")
    print(" |   |‾‾‾|     |  ˙||˙  |     |‾‾‾|   | ")
    print(" |   |__˙|     |___||___|     |˙__|   | ")
    print(" ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾ ")
    print("     WELCOME TO THE CULINARY CASTLE     ")
    print("    WHERE YOUR WISHES ARE OUR COMMAND   ")

def goodbye():
    print("                   /\                   ")
    print("    ###|          /  \       ###|       ")
    print("       |         /    \         |       ")
    print("       |        /      \        |       ")
    print("       /\      /  ____  \      /\       ")
    print("      /  \    /  |    |  \    /  \      ")
    print("     /    \  /   |‾‾‾‾|   \  /    \     ")
    print("    / ___  \/     ‾‾‾‾     \/  ___ \    ")
    print("   / |   |  |              |  |   | \   ")
    print("  /  |   |  |              |  |   |  \  ")
    print(" /    ‾‾‾                      ‾‾‾    \ ")
    print(" |             |‾‾‾||‾‾‾|             | ")
    print(" |             |   ||   |             | ")
    print(" |    ___      |___||___|      ___    | ")
    print(" |   |   |     |   ||   |     |   |   | ")
    print(" |   |‾‾‾|     |  ˙||˙  |     |‾‾‾|   | ")
    print(" |   |__˙|     |___||___|     |˙__|   | ")
    print(" ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾ ")
    print("         THANK YOU FOR COMING TO        ")
    print("           THE CULINARY CASTLE          ")
    print("          HAVE A FANTASTIC DAY          ")

